spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
  datasource:
    username: mrbean
    password: teddy
    url: jdbc:postgresql://localhost:5432/postgres

roommate:
  rollen:
    admin: hguelbol,ozanozden,nawiedk,Stelioo,houssem673